// Frontend-Next/src/core/layout/language-switcher.tsx
'use client';

import { Radio, RadioGroup } from '@headlessui/react';
import { useLocale, useTranslations } from 'next-intl';
import { useTransition } from 'react';
import { usePathname, useRouter } from '../i18n/navigation';
import { routing, type Locale } from '../i18n/routing';

export function LanguageSwitcher() {
  const t = useTranslations('language');
  const locale = useLocale() as Locale;
  const router = useRouter();
  const pathname = usePathname();
  const [isPending, startTransition] = useTransition();

  const change = (next: Locale) =>
    startTransition(() => {
      router.replace(pathname, { locale: next });
    });

  return (
    <RadioGroup
      value={locale}
      onChange={change}
      disabled={isPending}
      aria-label={t('label')}
      className="border-border bg-surface-muted inline-flex rounded-lg border p-0.5"
    >
      {routing.locales.map((value) => (
        <Radio
          key={value}
          value={value}
          aria-label={t(value)}
          lang={value}
          className="text-fg-muted hover:text-fg data-checked:bg-surface data-checked:text-primary data-checked:shadow-card data-focus:outline-focus flex h-9 min-w-10 cursor-pointer items-center justify-center rounded-md px-2 text-xs font-semibold uppercase transition-colors data-focus:outline-2"
        >
          {value}
        </Radio>
      ))}
    </RadioGroup>
  );
}

// Frontend-Angular/src/app/core/layout/language-switcher/language-switcher.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { Language, LanguageStore, SUPPORTED_LANGUAGES } from '../../i18n/language-store';

@Component({
  selector: 'app-language-switcher',
  imports: [TranslatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      role="radiogroup"
      [attr.aria-label]="'language.label' | translate"
      class="inline-flex rounded-lg border border-border bg-surface-muted p-0.5"
    >
      @for (language of languages; track language) {
        <button
          type="button"
          role="radio"
          [attr.aria-checked]="store.language() === language"
          [attr.aria-label]="'language.' + language | translate"
          [attr.lang]="language"
          (click)="select(language)"
          class="h-8 min-w-9 rounded-md px-2 text-xs font-semibold uppercase text-fg-muted transition-colors hover:text-fg aria-checked:bg-surface aria-checked:text-primary aria-checked:shadow-card"
        >
          {{ language }}
        </button>
      }
    </div>
  `,
})
export class LanguageSwitcher {
  protected readonly store = inject(LanguageStore);
  protected readonly languages = SUPPORTED_LANGUAGES;

  protected select(language: Language): void {
    void this.store.setLanguage(language);
  }
}
