// Frontend-Angular/src/app/features/dashboard/presentation/components/system-status-card/system-status-card.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { SkeletonModule } from 'primeng/skeleton';
import { LoadState } from '../../../../../shared/utils/load-state';
import { SystemHealth } from '../../../domain/entities/system-health';
import { DateTimePipe } from '../../../../../shared/pipes/date-time.pipe';

@Component({
  selector: 'app-system-status-card',
  imports: [DateTimePipe, TranslatePipe, SkeletonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="sh-card p-5" aria-labelledby="system-status-title" aria-live="polite">
      <div class="flex items-start justify-between gap-4">
        <h2 id="system-status-title" class="text-sm font-medium text-fg-muted">
          {{ 'dashboard.system.title' | translate }}
        </h2>
        <button
          type="button"
          class="flex size-8 items-center justify-center rounded-md text-fg-muted hover:bg-surface-muted hover:text-fg"
          [attr.aria-label]="'common.refresh' | translate"
          (click)="refresh.emit()"
        >
          <i class="pi pi-refresh" aria-hidden="true"></i>
        </button>
      </div>
      @switch (state().status) {
        @case ('success') {
          @if (health(); as h) {
            <p
              class="mt-3 flex items-center gap-2 text-2xl font-semibold"
              [class]="h.status === 'UP' ? 'text-success' : 'text-danger'"
            >
              <i
                [class]="'pi ' + (h.status === 'UP' ? 'pi-check-circle' : 'pi-times-circle')"
                aria-hidden="true"
              ></i>
              {{ 'dashboard.system.status.' + h.status | translate }}
            </p>
            <p class="mt-1 text-xs text-fg-muted">
              {{ 'dashboard.system.checkedAt' | translate }}
              {{ h.checkedAt | dateTime: 'time' }}
            </p>
          }
        }
        @case ('error') {
          <p class="mt-3 flex items-center gap-2 text-base font-medium text-danger" role="alert">
            <i class="pi pi-exclamation-circle" aria-hidden="true"></i>
            {{ 'dashboard.system.unreachable' | translate }}
          </p>
        }
        @default {
          <div class="mt-3 space-y-2" [attr.aria-label]="'common.loading' | translate">
            <p-skeleton width="8rem" height="2rem" />
            <p-skeleton width="10rem" height="0.75rem" />
          </div>
        }
      }
    </section>
  `,
})
export class SystemStatusCard {
  readonly state = input.required<LoadState<SystemHealth>>();
  readonly refresh = output<void>();

  protected readonly health = computed(() => {
    const state = this.state();
    return state.status === 'success' ? state.data : null;
  });
}

// Frontend-Next/src/features/system/presentation/components/system-status-card.tsx
'use client';

import {
  ArrowPathIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  XCircleIcon,
} from '@heroicons/react/24/outline';
import { useFormatter, useTranslations } from 'next-intl';
import { Skeleton } from '@/shared/ui/skeleton';
import { cn } from '@/shared/utils/cn';
import { useSystemHealth } from '../hooks/use-system-health';

export function SystemStatusCard() {
  const t = useTranslations('system');
  const tCommon = useTranslations('common');
  const format = useFormatter();
  const { data, isPending, isError, refetch, isFetching } = useSystemHealth();

  return (
    <section aria-labelledby="system-status-title" aria-live="polite" className="sh-card p-5">
      <div className="flex items-start justify-between gap-4">
        <h2 id="system-status-title" className="text-fg-muted text-sm font-medium">
          {t('title')}
        </h2>
        <button
          type="button"
          onClick={() => void refetch()}
          aria-label={tCommon('refresh')}
          className="text-fg-muted hover:bg-surface-muted hover:text-fg flex size-9 items-center justify-center rounded-md"
        >
          <ArrowPathIcon className={cn('size-5', isFetching && 'animate-spin')} aria-hidden="true" />
        </button>
      </div>

      {isPending && (
        <div className="mt-3 space-y-2" aria-label={tCommon('loading')}>
          <Skeleton className="h-8 w-32" />
          <Skeleton className="h-3 w-40" />
        </div>
      )}

      {isError && (
        <p role="alert" className="text-danger mt-3 flex items-center gap-2 text-base font-medium">
          <ExclamationCircleIcon className="size-5" aria-hidden="true" />
          {t('unreachable')}
        </p>
      )}

      {data && !isError && (
        <>
          <p
            className={cn(
              'mt-3 flex items-center gap-2 text-2xl font-semibold',
              data.status === 'UP' ? 'text-success' : 'text-danger',
            )}
          >
            {data.status === 'UP' ? (
              <CheckCircleIcon className="size-7" aria-hidden="true" />
            ) : (
              <XCircleIcon className="size-7" aria-hidden="true" />
            )}
            {t(`status.${data.status}`)}
          </p>
          <p className="text-fg-muted mt-1 text-xs">
            {t('checkedAt')} {format.dateTime(data.checkedAt, { timeStyle: 'medium' })}
          </p>
        </>
      )}
    </section>
  );
}
