// Frontend-Next/src/core/layout/user-menu.tsx
'use client';

import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/react';
import { ArrowRightStartOnRectangleIcon, KeyIcon } from '@heroicons/react/20/solid';
import { useTranslations } from 'next-intl';
import { logout } from '../auth/auth-api';
import { useSession } from '../auth/use-session';
import { APP_ROUTES } from '../config/routes/app.routes';
import { useRouter } from '../i18n/navigation';

export function UserMenu() {
  const t = useTranslations();
  const { session } = useSession();
  const router = useRouter();
  if (!session) return null;
  const initials = `${session.firstName.charAt(0)}${session.lastName.charAt(0)}`.toUpperCase();

  return (
    <Menu as="div" className="relative">
      <MenuButton
        aria-label={t('nav.userMenu')}
        className="bg-primary text-primary-fg data-focus:outline-focus flex size-9 items-center justify-center rounded-full text-xs font-semibold data-focus:outline-2 data-focus:outline-offset-2"
      >
        {initials}
      </MenuButton>
      <MenuItems
        anchor="bottom end"
        className="border-border bg-surface shadow-card z-50 mt-2 w-60 rounded-xl border p-1 [--anchor-gap:4px] focus:outline-none"
      >
        <div className="border-border mb-1 border-b px-3 py-2">
          <p className="text-fg truncate text-sm font-medium">
            {session.firstName} {session.lastName}
          </p>
          <p className="text-fg-muted truncate text-xs">{t(`roles.${session.role}`)}</p>
          {session.company && <p className="text-fg-muted truncate text-xs">{session.company.name}</p>}
        </div>
        <MenuItem>
          <button
            type="button"
            onClick={() => router.push(APP_ROUTES.CHANGE_PASSWORD)}
            className="text-fg data-focus:bg-surface-muted flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm"
          >
            <KeyIcon className="text-fg-muted size-4" aria-hidden="true" />
            {t('auth.changePassword.title')}
          </button>
        </MenuItem>
        <MenuItem>
          <button
            type="button"
            onClick={() => logout().finally(() => router.replace(APP_ROUTES.LOGIN))}
            className="text-danger data-focus:bg-surface-muted flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm"
          >
            <ArrowRightStartOnRectangleIcon className="size-4" aria-hidden="true" />
            {t('auth.logout')}
          </button>
        </MenuItem>
      </MenuItems>
    </Menu>
  );
}

// Frontend-Angular/src/app/core/layout/user-menu/user-menu.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { Router } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { MenuItem } from 'primeng/api';
import { MenuModule } from 'primeng/menu';
import { AuthStore } from '../../auth/auth-store';
import { APP_ROUTES } from '../../config/routes/app.routes';
import { LanguageStore } from '../../i18n/language-store';

@Component({
  selector: 'app-user-menu',
  imports: [MenuModule, TranslatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      class="flex items-center gap-2 rounded-lg p-1 pr-2 hover:bg-surface-muted"
      [attr.aria-label]="'nav.userMenu' | translate"
      aria-haspopup="menu"
      (click)="userMenu.toggle($event)"
    >
      <span
        class="flex size-8 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-fg"
        aria-hidden="true"
      >
        {{ initials() }}
      </span>
      <span class="hidden text-left text-sm leading-tight md:block">
        <span class="block font-medium text-fg">{{ auth.displayName() }}</span>
        <span class="block text-xs text-fg-muted">{{
          'roles.' + (auth.session()?.role ?? '') | translate
        }}</span>
      </span>
      <i class="pi pi-angle-down hidden text-xs text-fg-muted md:block" aria-hidden="true"></i>
    </button>
    <p-menu #userMenu [model]="items()" [popup]="true" appendTo="body" />
  `,
})
export class UserMenu {
  protected readonly auth = inject(AuthStore);
  private readonly router = inject(Router);
  private readonly translate = inject(TranslateService);
  private readonly language = inject(LanguageStore);

  protected readonly initials = computed(() => {
    const s = this.auth.session();
    return s ? `${s.firstName.charAt(0)}${s.lastName.charAt(0)}`.toUpperCase() : '';
  });

  protected readonly items = computed<MenuItem[]>(() => {
    this.language.language();
    const t = (key: string) => this.translate.instant(key) as string;
    return [
      { label: this.auth.session()?.email, disabled: true, styleClass: 'text-xs' },
      { separator: true },
      {
        label: t('auth.changePassword.title'),
        icon: 'pi pi-key',
        command: () => void this.router.navigateByUrl(APP_ROUTES.CHANGE_PASSWORD),
      },
      { label: t('auth.logout'), icon: 'pi pi-sign-out', command: () => this.logout() },
    ];
  });

  private logout(): void {
    this.auth.logout().subscribe(() => void this.router.navigateByUrl(APP_ROUTES.LOGIN));
  }
}
