// Frontend-Next/src/core/layout/theme-switcher.tsx
'use client';

import { Radio, RadioGroup } from '@headlessui/react';
import { ComputerDesktopIcon, MoonIcon, SunIcon } from '@heroicons/react/20/solid';
import { useTranslations } from 'next-intl';
import { useTheme } from 'next-themes';
import { useMounted } from '@/shared/hooks/use-mounted';
import type { ThemePreference } from '../config/theme/theme';

const OPTIONS = [
  { value: 'light', icon: SunIcon },
  { value: 'dark', icon: MoonIcon },
  { value: 'system', icon: ComputerDesktopIcon },
] as const satisfies ReadonlyArray<{ value: ThemePreference; icon: unknown }>;

export function ThemeSwitcher() {
  const t = useTranslations('theme');
  const { theme, setTheme } = useTheme();
  const mounted = useMounted();

  // The stored theme is unknown during SSR: reserve the space to avoid layout shift.
  if (!mounted) {
    return (
      <div
        aria-hidden="true"
        className="border-border bg-surface-muted h-[38px] w-[116px] rounded-lg border"
      />
    );
  }

  return (
    <RadioGroup
      value={(theme as ThemePreference | undefined) ?? 'system'}
      onChange={(value: ThemePreference) => setTheme(value)}
      aria-label={t('label')}
      className="border-border bg-surface-muted inline-flex rounded-lg border p-0.5"
    >
      {OPTIONS.map(({ value, icon: Icon }) => (
        <Radio
          key={value}
          value={value}
          aria-label={t(value)}
          title={t(value)}
          className="text-fg-muted hover:text-fg data-checked:bg-surface data-checked:text-primary data-checked:shadow-card data-focus:outline-focus flex size-9 cursor-pointer items-center justify-center rounded-md transition-colors data-focus:outline-2"
        >
          <Icon className="size-4" aria-hidden="true" />
        </Radio>
      ))}
    </RadioGroup>
  );
}

// Frontend-Angular/src/app/core/layout/theme-switcher/theme-switcher.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { ThemePreference, ThemeStore } from '../../theme/theme-store';

interface ThemeOption {
  readonly value: ThemePreference;
  readonly icon: string;
}

@Component({
  selector: 'app-theme-switcher',
  imports: [TranslatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      role="radiogroup"
      [attr.aria-label]="'theme.label' | translate"
      class="inline-flex rounded-lg border border-border bg-surface-muted p-0.5"
    >
      @for (option of options; track option.value) {
        <button
          type="button"
          role="radio"
          [attr.aria-checked]="theme.preference() === option.value"
          [attr.aria-label]="'theme.' + option.value | translate"
          [title]="'theme.' + option.value | translate"
          (click)="theme.setPreference(option.value)"
          class="flex size-8 items-center justify-center rounded-md text-fg-muted transition-colors hover:text-fg aria-checked:bg-surface aria-checked:text-primary aria-checked:shadow-card"
        >
          <i [class]="'pi ' + option.icon" aria-hidden="true"></i>
        </button>
      }
    </div>
  `,
})
export class ThemeSwitcher {
  protected readonly theme = inject(ThemeStore);
  protected readonly options: readonly ThemeOption[] = [
    { value: 'light', icon: 'pi-sun' },
    { value: 'dark', icon: 'pi-moon' },
    { value: 'system', icon: 'pi-desktop' },
  ];
}
